"""empty message

Revision ID: 451fb566f293
Revises: 66ed1426c92e
Create Date: 2021-03-10 18:20:32.201533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451fb566f293'
down_revision = '66ed1426c92e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Genre_name_key', 'Genre', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Genre_name_key', 'Genre', ['name'])
    # ### end Alembic commands ###
