"""empty message

Revision ID: 61eae3d02c38
Revises: 451fb566f293
Create Date: 2021-03-15 16:29:01.034779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61eae3d02c38'
down_revision = '451fb566f293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    op.add_column('Genre', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.alter_column('Genre', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'Genre', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Genre', type_='foreignkey')
    op.alter_column('Genre', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Genre', 'artist_id')
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
